[package]
name = "rust_stack_string_bench"
version = "0.1.0"
authors = ["Pascal Seitz <pascal.seitz@sap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bench]]
name = "bench"
